# Generated by Django 4.2.29 on 2026-04-28 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logbook', '0003_logtemplate_logattachment'),
        ('placements', '0004_alter_internshipplacement_academic_supervisor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_log_submitted', models.BooleanField(default=True)),
                ('email_log_reviewed', models.BooleanField(default=True)),
                ('email_placement_updates', models.BooleanField(default=True)),
                ('inapp_log_submitted', models.BooleanField(default=True)),
                ('inapp_log_reviewed', models.BooleanField(default=True)),
                ('inapp_placement_updates', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('log_submitted', 'Log Submitted'), ('log_assigned', 'Log Assigned'), ('log_reviewed', 'Log Reviewed'), ('log_approved', 'Log Approved'), ('log_returned', 'Log Returned'), ('placement_assigned', 'Placement Assigned'), ('placement_status', 'Placement Status Updated'), ('general', 'General')], default='general', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='logbook.weeklylog')),
                ('related_placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='placements.internshipplacement')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
