# Generated by Django 4.2.29 on 2026-03-24 13:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_score', models.DecimalField(decimal_places=2, help_text='Workplace supervisor component (40%)', max_digits=5)),
                ('academic_score', models.DecimalField(decimal_places=2, help_text='Academic supervisor component (30%)', max_digits=5)),
                ('logbook_score', models.DecimalField(decimal_places=2, help_text='Logbook component (30%)', max_digits=5)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, choices=[('A', 'A (Distinction)'), ('B', 'B (Credit)'), ('C', 'C (Pass)'), ('D', 'D (Marginal Pass)'), ('F', 'F (Fail)')], max_length=1)),
                ('comments', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'evaluations',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('weight_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Evaluation Criteria',
                'db_table': 'evaluation_criteria',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_awarded', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='evaluations.evaluationcriteria')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_scores', to='evaluations.evaluation')),
            ],
            options={
                'db_table': 'evaluation_scores',
            },
        ),
    ]
