# Generated by Django 4.2.29 on 2026-04-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('activities', models.TextField(help_text='Activities performed during the week')),
                ('challenges', models.TextField(blank=True, help_text='Challenges encountered')),
                ('skills_learned', models.TextField(blank=True, help_text='Skills learned or developed')),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('returned', 'Returned'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'weekly_logs',
                'ordering': ['placement', 'week_number'],
            },
        ),
    ]
