# Generated by Django 4.2.29 on 2026-04-03 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logbook', '0001_initial'),
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylog',
            name='placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_logs', to='placements.internshipplacement'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklylog',
            unique_together={('placement', 'week_number')},
        ),
    ]
