# Generated by Django 4.2.29 on 2026-04-16 19:08

from django.db import migrations, models
import django.db.models.deletion
import logbook.models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('activities_prompts', models.JSONField(default=list, help_text='List of guiding prompts for activities section')),
                ('challenges_prompts', models.JSONField(default=list, help_text='List of guiding prompts for challenges section')),
                ('skills_prompts', models.JSONField(default=list, help_text='List of guiding prompts for skills learned section')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'log_templates',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LogAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=logbook.models.log_attachment_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('caption', models.CharField(blank=True, help_text='Brief description of the attachment', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='logbook.weeklylog')),
            ],
            options={
                'db_table': 'log_attachments',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
