# Generated by Django 4.2.29 on 2026-04-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_logtemplate_logattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylog',
            name='computed_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average score from supervisor reviews (0-100%)', max_digits=5, null=True),
        ),
    ]
