# Generated by Django 4.2.29 on 2026-03-24 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logbook', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('target_model', models.CharField(max_length=100)),
                ('target_id', models.PositiveIntegerField()),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('returned', 'Returned for Revision')], max_length=20)),
                ('comments', models.TextField(help_text='Review comments and feedback')),
                ('rating', models.PositiveIntegerField(blank=True, help_text='Optional rating out of 10', null=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='logbook.weeklylog')),
            ],
            options={
                'db_table': 'supervisor_reviews',
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
