# Generated by Django 4.2.29 on 2026-04-25 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logbook', '0003_logtemplate_logattachment'),
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorreview',
            name='reviewer_type',
            field=models.CharField(choices=[('workplace', 'Workplace Supervisor'), ('academic', 'Academic Supervisor')], default='workplace', help_text='Type of supervisor giving this review', max_length=20),
        ),
        migrations.AlterField(
            model_name='supervisorreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='supervisorreview',
            unique_together={('log', 'reviewer_type')},
        ),
    ]
