# Generated by Django 4.2.29 on 2026-04-29 00:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_add_reviewer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisorreview',
            name='rating',
        ),
        migrations.AddField(
            model_name='supervisorreview',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Score for this log (0-100%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
