# Generated by Django 4.2.29 on 2026-04-16 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import placements.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('placements', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('placement_letter', 'Placement Letter'), ('student_id', 'Student ID'), ('agreement', 'Agreement'), ('insurance', 'Insurance Certificate'), ('other', 'Other')], default='other', max_length=30)),
                ('file', models.FileField(upload_to=placements.models.placement_document_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='placements.internshipplacement')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_placement_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'placement_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
